all: IoT-device_demo

PROJECT_SOURCEFILES += sensor.c

MODULES += os/net/app-layer/mqtt

CONTIKI = ../..
#CFLAGS	+= -Wno-nonnull-compare -Wno-implicit-function-declaration

include $(CONTIKI)/Makefile.include
